### ISSUE TITLE
Тестирование

### ISSUE THREAD

**Issue by silverghost63** [NikitaSardov/projects#2]
Добрый вечер.
На широком мониторе (1920px) изображения внизу сдвигаются
https://yadi.sk/i/MI5AyKaIqc8g5
Можно сделать так:

```
.footer__element1,
.footer__element2 {
  background-size: cover;
}
```

**Comment by nikitasardov** [comment]
Спасибо! Исправил странное свойство {background-image-size: cover;} на {background-size: cover;}. Теперь все адекватно сдвигается.

**Comment by gitwood** [comment]
Привет ,  проверила проект , в целом понравился , вот итоги
1. проект адаптивен , результат теста pagespeed для мобильных = 100 
2. файлы css сжаты 
3. скорость pagespeed= 86 
4. использованы комментарии кода !
5. использованы анимации - трансформации scale, rotate и др.
6. весь css код поделен на 2 части , 1 часть загружается в header , вторая часть кода загружается перед тегом body
